import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.170'
    id "com.modrinth.minotaur" version "2.+"
    id 'net.darkhax.curseforgegradle' version '1.1.+'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

def changelogText = rootProject.file('changelog.md').text

version = mod_version
group = mod_group_id

repositories {
    mavenCentral()

    // NeoForge repository
    maven {
        url = "https://maven.neoforged.net/releases/"
    }

    // Modrinth repository
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven/"
        content {
            includeGroup "maven.modrinth"
        }
    }

    // Max Henkel's Maven repository
    maven {
        url = "https://maven.maxhenkel.de/repository/public/"
    }

    maven {
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}



base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    implementation "curse.maven:sound-physics-remastered-535489:5991573"
    implementation "de.maxhenkel.voicechat:voicechat-api:${voicechat_api_version}"
    runtimeOnly "maven.modrinth:simple-voice-chat:neoforge-${voicechat_version}"


}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    dependsOn jar

    apiToken = System.getenv("CURSEFORGE_TOKEN")

    def mainFile = upload('1173633', file("build/libs/${mod_id}-${mod_version}.jar"))
    mainFile.displayName = "${mod_name}-${mod_version}"
    mainFile.releaseType = 'release'
    mainFile.changelog = changelogText

    mainFile.addRequirement("simple-voice-chat")
    mainFile.addOptional("vics-point-blank")
    mainFile.addOptional("sound-physics-remastered")
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "voiceless-survival"
    versionName = "${mod_name} ${mod_version}"
    versionNumber = "${mod_version}"
    versionType = "release"
    uploadFile = file("build/libs/${mod_id}-${mod_version}.jar")
    gameVersions = ["${minecraft_version}"] as Iterable<? extends String>
    loaders = ["neoforge"]
    changelog = changelogText


    dependencies { // A special DSL for creating dependencies
        required.project 'simple-voice-chat'
        optional.project 'vics-point-blank'
        optional.project 'sound-physics-remastered'
    }
}

tasks.register('publicModdedSite') {
    dependsOn 'build'
    dependsOn 'publishCurseForge'
    dependsOn 'modrinth'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}