modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved by armilp"
[[mods]]
modId="ezvcsurvival"
version="0.0.5"
displayName="Voiceless Survival"
authors="armilp"
description='''${mod_description}'''
[[dependencies.ezvcsurvival]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.ezvcsurvival]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.ezvcsurvival]]
modId="voicechat"
mandatory=true
versionRange="[1.20.1-2.5.27,)"
ordering="AFTER"
side="BOTH"
