modLoader = "javafml"
loaderVersion = "[4,)"
license = "ARR"
issueTrackerURL = "https://github.com/armilp02/Voiceless-Survival/issues"

[[mods]]
modId = "ezvcsurvival"
version = "1.21.1-0.8.2"
displayName = "Voiceless Survival"
description = '''
A survival mod for Minecraft with voice chat integration and enhanced gameplay.
'''

authors = "armilp"
[[dependencies.ezvcsurvival]]
modId = "neoforge"
type = "required"
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ezvcsurvival]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ezvcsurvival]]
modId = "voicechat"
type = "required"
versionRange = "[1.21.1-2.5.0,)"
ordering = "AFTER"
side = "BOTH"
